version: '3'

services:

  endpoint:
    build:
        context: ./platform_in/
        dockerfile: Dockerfile.prod
    #command: gunicorn --bind 0.0.0.0:5003 manage:app
    expose:
      - 5000
    env_file:
      - app_config.env
    environment:
      - ca=chain.pem
      - cert=service.cert
      - key=service.key
      - LOG_LEVEL=2

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - endpoint
